export const testimonials = [
  "I have joined her sessions she is amazing very structured workout sessions where all types of people can join. In love with the morning sessions where you can burn 300-400 cal easily. Highly recommend...",
  "For anyone looking to get fitter, I highly recommend Prapti. I have been a part of her fitness family since January. In 4 months, I have achieved: 1. Immense improvement in core and lower body strengt...",
  "An angel in disguise  I started Prapti ' s sessions soon after my physiotherapy for neck pain was completed. I could barely hold my planks for a few seconds. I have hated going to the gym. I had dec...",
  "Very professional and supportive programme Prapti is very professional in her approach. Her approach to exercises is very supportive as one always have a choice to do higher or lower intensity. The fl...",
  "Prapti is Fantastic and very… Prapti is Fantastic and very professional. She inspired me to start working out . With kids this online sessions have made my life easier. Can’t thank her enough ...",
  "Prapti is an awesome fitness coach - the best I have met! Keep inspiring and motivating people to achieve their fitness goals and adopt a healthy lifestyle. In love with her unique exercises and simpl...",
  "I have recently joined Prapti’s fitness classes and really I am not one of those self motivated people who do regular excercises. But whenever I attend the class which is normally 2-3 times a week it’...",
  "Thank you Prapti for consistently designing and training us on our fitness missions. In just 6 weeks, I believe I can achieve a better body despite my medical conditions with your guided diet plans an...",
  "Amazing full body online sessions. Could feel the pain(good one!) after each session. You are great Prapti so as your style of training. All the best.....",
  "Prapti is a fantastic fitness instructor. Her sessions are so varied and fun. She is motivating and she always helps to push me to do my best. Prapti's online fitness sessions were a god sent to me in...",
  "Excellent and effective work outs Excellent and effective work outs ! Prapti is incredibly inspirational and her work outs are just what you need if you want to build stamina and lose weight …! I high...",
  "This recommendation is for Prapti for the super awesome workout sessions that she conducts on daily basis. I must say these are just not any random session that we see online, these are power packed s...",
  "Prapti’s one to one sessions are very good and tailor made to suit one’s requirement. She is dedicated and has been very helpful in building my strength and weight loss. I would definitely recommend h...",
  "Prapti is the best mentor you can have to reach your fitness goal..it's been just 3 weeks I started following Prapti's diet chart and her high intensity session and must say it works like charm and I ...",
  "I highly recommend Prapti’s Workout sessions. They are so intense, lots of variety. No session is the same. I have been doing her sessions since May2020 and i love it. I have improved on my stamina , ...",
  "Prapti and her amazing body has really motivated me keep fit and reduce weight. Her classes are really good. My journey on the platform of fitness has started and it will end when I reach my destinati...",
  "One of the most excellent service and… You all feel welcomed and look forward to her sessions. Her advice her motivations are up to the top, from her busy life, kids she never is late for her sessions...",
  "You really get results in a short space of time! From the moment I saw Prapti's advert on Facebook to being part of her 6 week challenge, I haven't regretted it one bit! She is motivated, passionate a...",
  "The best thing about keep well mantra… He best thing about keep well mantra is the variety and the community of like minded enthusiasts. You never feel the sense of monotony in the workouts … there’s ...",
  "I joined your program when i was 86 kg and now i am 69 after your exercise and controlled diet…Raveena shared some diet tips along with your daily classes … my weight loss journey got easier … and the...",
  "I can't believe how far I have come on my fitness journey, and I owe it all to Prapti's incredible home workouts!\nFrom day one, I've been addicted to these workouts because they're not just exercises,...",
  "Hi Prapti, as you know this time I am taking a holiday break. Not sure if that was wise as I miss you and the workouts every single day. \nI was also reflecting, that the thing I am most proud of mys...",
  "Finally got a pair of size 12 trousers and they fit me! Mummy tummy is still an issue but comparing it to last year November… can see a massive difference ( from size 14-16 to now 12)  @Prapti PT I am...",
  "Without you, we look for excuses not to exercise. With you, we look forward to exercising. YOU make it fun and interesting, and WE get results. Your sessions are addictive and even after finishing one...",
  "Just wanted to share my progress after completing two 6 week challenges with Prapti, the first one in February and then second starting in May after a small break in between. I signed up for nutritio...",
  "8 weeks into the journey with Prapti.: Wanted to give a quick update. \n\nLost about 3-3.5kgs \nI have foolishly not measured myself at the start of the journey and therefore don’t have an objective numb...",
  "I joined Prapti’s workout plan from mid May but I was not very regular due to family members all around ( to put it right I felt a bit conscious). Started doing her workout sessions more regularly fro...",
  "I hate exercising too and joined Prapti Dutts program last year and it really transformed me and my thinking about fitness and exercising in general. \nI would definitely recommend trying one of Prapti...",
  "So I have completed my 6 weeks diet and exercise programme. No change on the scale though 17 inches overall body lost! Abdominal definition beginning to show.. most importantly, so many exercises got ...",
  "When I delivered the baby in december, I never thought I will ever be like pre pregnancy and hated my body and stopped taking pictures. I felt so unsexy if that was a word . Left side is me in April...",
  "I wonder if you have any idea, how many spirits you raise by empowering us women who are so culturally attuned to put ourselves last, you are creating a space for us to feel powerful, positive, happy ...",
  "Prapti Dutt, you are the Angel who is changing my fitness!\nStarted with Prapti on fitness journey & she is totally supportive towards old injuries & bad knees- her exercises are superb & albeit I have...",
  "Prapti Dutt’ insight into nutrition is commendable. I had a health condition and mostly anaemic for prolonged time. That has changed for the first time. No two sessions are similar and they are fun. ...",
  "What should I say about Prapti Dutt and her classes words fall short...she is a magician made my stubborn fat melt and gives me that push needed to achieve my fitness goals...she has been a mentor and...",
  "Prapti Dutt , love your sessions! So glad that I signed up for your sessions. I'm never going to think of going to the gym now....",
  "Never knew fitness workouts could be so much fun and motivating at the same time! I bought 2 challenges in one go I think! \nYou are not just an inspiration to other women, but genuinely a warm and...",
  "Such an inspirational story Prapti Dutt . You indeed motivate and inspire others to stay fit and I do love your classes with variations. All the best . Hoping to have these classes as a lifestyle chan...",
  "I would highly recommend Prapti Dutt, I am two weeks into the 6 week challenge and have noticed a lot of improvements. I get bored easily with diets and exercise however prapti’s workouts are amazing ...",
  "Highly highly recommend your sessions ! You are so inspiring and committed and having done 3 challenges, I am so so pleased with in my fitness and stamina ... looking forward the next challenge .... t...",
  "Signed up for 6 weeks and lost 10 lbs and gained the love for excercising regularly and maintaining a consistent healthy diet routine  thank you Prapti Dutt you truly epitomize that women when suppo...",
  "I started Prapti’s classes at a very low point in my life .. physically my stamina was nowhere what it used to be before pregnancy and an obvious sense of low esteem . And I am so glad she has changed...",
  "My Fitness Guru who has injected fitness addiction in me. I have started to love myself by keeping myself physically and mentally fit by her contagious workout sessions. Can’t wait for the next challe...",
  "I can’t thank you enough for motivating me so much, you are a true inspiration.. I’m much stronger than i was and much determined than i was before i did your classes.. being on the community is what ...",
  "Prapti you are an inspiration for so many of us! I love the variations in your workouts and resistance training is my favorite. I will be signing up for next challenge to continue my fitness journey...",
  "I am so fortunate to have found Prapti through this group!! She has shown me that anything is possible and given me hope and strength and a will to keep going to achieve my best potential- for that I ...",
  "I’m not an Asian person and I hope you don’t mind me posting. It took me awhile to commit to Prapti training but in less than 2 weeks I have done 10 training sessions and there is 1kg less of me. And ...",
  "I love your classes and your (our online community) so so much that it’s like an addiction now .. can’t get enough. I have been with you since July 2021 and looking forward to the next challenge. I am...",
  "I seriously mean from the bottom of my heart when I thank you my lovely. I have wasted so much money getting yearly memberships of gym and going not even for a month. You sessions are so much fun and ...",
  "I have done one challenge back in November lost 3kg. Prapti is amazing, made me believe in myself. Thanks Prapti and I am\nJoining again as I am not done yet with my weight loss....",
  "From being a non exercising person to falling in lobe with it! Is all because of you Prapti Your story is really inspiring, it proves nothing's impossible if you have the Madness! Love your extras...",
  "Prapti finding you and your classes have been the biggest blessing in 2022!! You are an amazing instructor and more importantly a wonderful human being! The community you have created of inspiring wom...",
  "Prapti I will soon be completing my 1year anniversary with u n the challenges which is a testimony to how much I m hooked on to the classes and your energy! I tend to get bored easily n u have done a ...",
  "Prapti Dutt so glad I made the move to join you. Your classes are never boring and always different. I never thought I would be able to train alone but you have instilled something in me that makes me...",
  "Prapti is extremely professional & organised physical trainer. She listens and tailors training programs based on individual needs and life styles . She motivates us really well and is very flexible t...",
  "I’ve now had 4 sessions with Prapti- she is great! She knows exactly how hard to push me and I am so pleased I signed up to it. I look forward to starting the weekend classes too, now that all my week...",
  "I am fairly new to the sessions & I keep coming for more. I love the stretches & can feel the burn . Prapti is an amazing , kind & gentle mentor . I like the way she motivates you to go that extra mil...",
  "It’s only been less than 2 weeks since I first started with Prapti’s fitness sessions but it has completely changed my perspective about fitness. I might not be very regular but whatever sessions I ha...",
  "Prapti is really professional and organises structured fitness sessions.. I like the personal touch in the sessions even when doing them virtually.. once you begin working out with her you would feel ...",
  "I highly recommend Prapti. It's been couple of months that I started workout with her online and I would like to mention, she is amazing. I am kind of one who doesn't easily invest and continue with w...",
  "Prapti’s fitness regimes are just the perfect start to my mornings. Not an early riser but her beautifully balanced workouts have been something I have started looking forward to everyday... after ini...",
  "Excellent upper body strength session Excellent upper body strength session. This session had a good mix of core, glutes and pelvic floor exercises. I loved the session :)...",
  "My 3 months journey from fat to fit. I would say so as 3 months ago Walking up the stairs was a gruesome task for me. But now I can run up and down . All because of you. I have lost 9 kg so far but ...",
  "Prapti - you are an amazing trainer.Your positive attitude has really kept me going and made me get into a routine. I am enjoying the training so much and am very grateful for your support. Your inval...",
  "Prapti's passion for fitness is infectious and her own transformation is inspiring. She offers a variety of options to train with her: zoom sessions, 1-2-1, group sessions, buggyfit sessions in the pa...",
  "I love Prapti's fitness challenges. Each session had a particular focus (upper, lower, stamina, ...) and is super fun and easy to follow. Goal setting and tracking is mostly self-organized but Prapti ...",
  "Excellent PT- highly recommend Excellent PT. Helped me lose 10kgs postpartum through workout and diet. Would highly recommend....",
  "Loving the workout sessions Loving the workout sessions. The combination of exercises has given me a boost of energy and got me into a routine. Looking forward to many more sessions. Good job Prapti....",
  "Feeling strong and motivated! His is the place where I found myself, to get more healthier, strong and motivated. I’m part of the fitness challenge and I experienced that the workouts and consistency ...",
  "Coming out of Prapti fitness classes I feel energised, happy and ready to start my day. She really pushes you and focuses on the core body areas. I would highly recommend Prapti....",
  "Varied classes with lots of flex Prapti's classes are wonderfully varied. You'll never get bored of the same routine as each class is different. She gives options of easy/hard on every exercise which ...",
  "Prapti is absolutely fantastic !!! She is one of the good things that happened to me during Lockdown. I have been doing her sessions since July and I just love it. Her sessions are not the same, as th...",
  "I have had an amazing transformation after joining the KeepWell Mantra Fitness Routine and Diet Consultations. I managed to hit my weight goal, strengthen my core and increase stamina within the first...",
  "Prapti is amazing fitness trainer. She is professional, highly skilled and organised in her regimes. Many got desirable body transformations by following Prapti’s diverse fitness classes. She is motiv...",
  "One of the most excellent service and… You all feel welcomed and look forward to her sessions. Her advice her motivations are up to the top, from her busy life, kids she never is late for her sessions...",
  "Highly recommended! Prapti is so dedicated, she really motivates you like none other I've sen before. Truly an inspiration. Her exercises are also really challenging but doable and simultaneously full...",
  "Prapti dutt is a amazing trainer Prapti dutt is a amazing trainer, knowledgable, experienced.She works well with her clients and give personal attention to everyones needs and requirements. She has ch...",
  "Amazing experience! Prapti is a true professional who is able to work towards YOUR fitness goals. Her workouts are gruelling but fun, with no two sessions ever the same! Inspirational lady who is cons...",
  "Fantastic trainer Fantastic trainer. Very professional and variety of exercises to choose from. Amazing transformations ...",
  "Ladies highly recommend Keep Well Mantras if you're looking to improve your fitness journey. This community is for ladies/mums who fancy joining a fitness community from the comfort of their home.The ...",
  "I have joined her sessions she is amazing very structured workout sessions where all types of people can join. In love with the morning sessions where you can burn 300-400 cal easily. Highly recommend...",
  "For anyone looking to get fitter, I highly recommend Prapti. I have been a part of her fitness family since January. In 4 months, I have achieved: 1. Immense improvement in core and lower body strengt...",
  "An angel in disguise  I started Prapti ' s sessions soon after my physiotherapy for neck pain was completed. I could barely hold my planks for a few seconds. I have hated going to the gym. I had dec...",
  "Very professional and supportive programme Prapti is very professional in her approach. Her approach to exercises is very supportive as one always have a choice to do higher or lower intensity. The fl...",
  "Prapti is Fantastic and very… Prapti is Fantastic and very professional. She inspired me to start working out . With kids this online sessions have made my life easier. Can’t thank her enough ...",
  "Prapti is an awesome fitness coach - the best I have met! Keep inspiring and motivating people to achieve their fitness goals and adopt a healthy lifestyle. In love with her unique exercises and simpl...",
  "I have recently joined Prapti’s fitness classes and really I am not one of those self motivated people who do regular excercises. But whenever I attend the class which is normally 2-3 times a week it’...",
  "Thank you Prapti for consistently designing and training us on our fitness missions. In just 6 weeks, I believe I can achieve a better body despite my medical conditions with your guided diet plans an...",
  "Amazing full body online sessions. Could feel the pain(good one!) after each session. You are great Prapti so as your style of training. All the best.....",
  "Prapti is a fantastic fitness instructor. Her sessions are so varied and fun. She is motivating and she always helps to push me to do my best. Prapti's online fitness sessions were a god sent to me in...",
  "Excellent and effective work outs Excellent and effective work outs ! Prapti is incredibly inspirational and her work outs are just what you need if you want to build stamina and lose weight …! I high...",
  "This recommendation is for Prapti for the super awesome workout sessions that she conducts on daily basis. I must say these are just not any random session that we see online, these are power packed s...",
  "Prapti’s one to one sessions are very good and tailor made to suit one’s requirement. She is dedicated and has been very helpful in building my strength and weight loss. I would definitely recommend h...",
  "Prapti is the best mentor you can have to reach your fitness goal..it's been just 3 weeks I started following Prapti's diet chart and her high intensity session and must say it works like charm and I ...",
  "I highly recommend Prapti’s Workout sessions. They are so intense, lots of variety. No session is the same. I have been doing her sessions since May2020 and i love it. I have improved on my stamina , ...",
  "Prapti and her amazing body has really motivated me keep fit and reduce weight. Her classes are really good. My journey on the platform of fitness has started and it will end when I reach my destinati...",
  "One of the most excellent service and… You all feel welcomed and look forward to her sessions. Her advice her motivations are up to the top, from her busy life, kids she never is late for her sessions...",
  "You really get results in a short space of time! From the moment I saw Prapti's advert on Facebook to being part of her 6 week challenge, I haven't regretted it one bit! She is motivated, passionate a...",
  "The best thing about keep well mantra… He best thing about keep well mantra is the variety and the community of like minded enthusiasts. You never feel the sense of monotony in the workouts … there’s ...",
  "I joined your program when i was 86 kg and now i am 69 after your exercise and controlled diet…Raveena shared some diet tips along with your daily classes … my weight loss journey got easier … and the...",
  "I can't believe how far I have come on my fitness journey, and I owe it all to Prapti's incredible home workouts!\nFrom day one, I've been addicted to these workouts because they're not just exercises,...",
  "Hi Prapti, as you know this time I am taking a holiday break. Not sure if that was wise as I miss you and the workouts every single day. \nI was also reflecting, that the thing I am most proud of mys...",
  "Finally got a pair of size 12 trousers and they fit me! Mummy tummy is still an issue but comparing it to last year November… can see a massive difference ( from size 14-16 to now 12)  @Prapti PT I am...",
  "Without you, we look for excuses not to exercise. With you, we look forward to exercising. YOU make it fun and interesting, and WE get results. Your sessions are addictive and even after finishing one...",
  "Just wanted to share my progress after completing two 6 week challenges with Prapti, the first one in February and then second starting in May after a small break in between. I signed up for nutritio...",
  "8 weeks into the journey with Prapti.: Wanted to give a quick update. \n\nLost about 3-3.5kgs \nI have foolishly not measured myself at the start of the journey and therefore don’t have an objective numb...",
  "I joined Prapti’s workout plan from mid May but I was not very regular due to family members all around ( to put it right I felt a bit conscious). Started doing her workout sessions more regularly fro...",
  "I hate exercising too and joined Prapti Dutts program last year and it really transformed me and my thinking about fitness and exercising in general. \nI would definitely recommend trying one of Prapti...",
  "So I have completed my 6 weeks diet and exercise programme. No change on the scale though 17 inches overall body lost! Abdominal definition beginning to show.. most importantly, so many exercises got ...",
  "When I delivered the baby in december, I never thought I will ever be like pre pregnancy and hated my body and stopped taking pictures. I felt so unsexy if that was a word . Left side is me in April...",
  "I wonder if you have any idea, how many spirits you raise by empowering us women who are so culturally attuned to put ourselves last, you are creating a space for us to feel powerful, positive, happy ...",
  "Prapti Dutt, you are the Angel who is changing my fitness!\nStarted with Prapti on fitness journey & she is totally supportive towards old injuries & bad knees- her exercises are superb & albeit I have...",
  "Prapti Dutt’ insight into nutrition is commendable. I had a health condition and mostly anaemic for prolonged time. That has changed for the first time. No two sessions are similar and they are fun. ...",
  "What should I say about Prapti Dutt and her classes words fall short...she is a magician made my stubborn fat melt and gives me that push needed to achieve my fitness goals...she has been a mentor and...",
  "Prapti Dutt , love your sessions! So glad that I signed up for your sessions. I'm never going to think of going to the gym now....",
  "Never knew fitness workouts could be so much fun and motivating at the same time! I bought 2 challenges in one go I think! \nYou are not just an inspiration to other women, but genuinely a warm and...",
  "Such an inspirational story Prapti Dutt . You indeed motivate and inspire others to stay fit and I do love your classes with variations. All the best . Hoping to have these classes as a lifestyle chan...",
  "I would highly recommend Prapti Dutt, I am two weeks into the 6 week challenge and have noticed a lot of improvements. I get bored easily with diets and exercise however prapti’s workouts are amazing ...",
  "Highly highly recommend your sessions ! You are so inspiring and committed and having done 3 challenges, I am so so pleased with in my fitness and stamina ... looking forward the next challenge .... t...",
  "Signed up for 6 weeks and lost 10 lbs and gained the love for excercising regularly and maintaining a consistent healthy diet routine  thank you Prapti Dutt you truly epitomize that women when suppo...",
  "I started Prapti’s classes at a very low point in my life .. physically my stamina was nowhere what it used to be before pregnancy and an obvious sense of low esteem . And I am so glad she has changed...",
  "My Fitness Guru who has injected fitness addiction in me. I have started to love myself by keeping myself physically and mentally fit by her contagious workout sessions. Can’t wait for the next challe...",
  "I can’t thank you enough for motivating me so much, you are a true inspiration.. I’m much stronger than i was and much determined than i was before i did your classes.. being on the community is what ...",
  "Prapti you are an inspiration for so many of us! I love the variations in your workouts and resistance training is my favorite. I will be signing up for next challenge to continue my fitness journey...",
  "I am so fortunate to have found Prapti through this group!! She has shown me that anything is possible and given me hope and strength and a will to keep going to achieve my best potential- for that I ...",
  "I’m not an Asian person and I hope you don’t mind me posting. It took me awhile to commit to Prapti training but in less than 2 weeks I have done 10 training sessions and there is 1kg less of me. And ...",
  "I love your classes and your (our online community) so so much that it’s like an addiction now .. can’t get enough. I have been with you since July 2021 and looking forward to the next challenge. I am...",
  "I seriously mean from the bottom of my heart when I thank you my lovely. I have wasted so much money getting yearly memberships of gym and going not even for a month. You sessions are so much fun and ...",
  "I have done one challenge back in November lost 3kg. Prapti is amazing, made me believe in myself. Thanks Prapti and I am\nJoining again as I am not done yet with my weight loss....",
  "From being a non exercising person to falling in lobe with it! Is all because of you Prapti Your story is really inspiring, it proves nothing's impossible if you have the Madness! Love your extras...",
  "Prapti finding you and your classes have been the biggest blessing in 2022!! You are an amazing instructor and more importantly a wonderful human being! The community you have created of inspiring wom...",
  "Prapti I will soon be completing my 1year anniversary with u n the challenges which is a testimony to how much I m hooked on to the classes and your energy! I tend to get bored easily n u have done a ...",
  "Prapti Dutt so glad I made the move to join you. Your classes are never boring and always different. I never thought I would be able to train alone but you have instilled something in me that makes me...",
  "Prapti is extremely professional & organised physical trainer. She listens and tailors training programs based on individual needs and life styles . She motivates us really well and is very flexible t...",
  "I’ve now had 4 sessions with Prapti- she is great! She knows exactly how hard to push me and I am so pleased I signed up to it. I look forward to starting the weekend classes too, now that all my week...",
  "I am fairly new to the sessions & I keep coming for more. I love the stretches & can feel the burn . Prapti is an amazing , kind & gentle mentor . I like the way she motivates you to go that extra mil...",
  "It’s only been less than 2 weeks since I first started with Prapti’s fitness sessions but it has completely changed my perspective about fitness. I might not be very regular but whatever sessions I ha...",
  "Prapti is really professional and organises structured fitness sessions.. I like the personal touch in the sessions even when doing them virtually.. once you begin working out with her you would feel ...",
  "I highly recommend Prapti. It's been couple of months that I started workout with her online and I would like to mention, she is amazing. I am kind of one who doesn't easily invest and continue with w...",
  "Prapti’s fitness regimes are just the perfect start to my mornings. Not an early riser but her beautifully balanced workouts have been something I have started looking forward to everyday... after ini...",
  "Excellent upper body strength session Excellent upper body strength session. This session had a good mix of core, glutes and pelvic floor exercises. I loved the session :)...",
  "My 3 months journey from fat to fit. I would say so as 3 months ago Walking up the stairs was a gruesome task for me. But now I can run up and down . All because of you. I have lost 9 kg so far but ...",
  "Prapti - you are an amazing trainer.Your positive attitude has really kept me going and made me get into a routine. I am enjoying the training so much and am very grateful for your support. Your inval...",
  "Prapti's passion for fitness is infectious and her own transformation is inspiring. She offers a variety of options to train with her: zoom sessions, 1-2-1, group sessions, buggyfit sessions in the pa...",
  "I love Prapti's fitness challenges. Each session had a particular focus (upper, lower, stamina, ...) and is super fun and easy to follow. Goal setting and tracking is mostly self-organized but Prapti ...",
  "Excellent PT- highly recommend Excellent PT. Helped me lose 10kgs postpartum through workout and diet. Would highly recommend....",
  "Loving the workout sessions Loving the workout sessions. The combination of exercises has given me a boost of energy and got me into a routine. Looking forward to many more sessions. Good job Prapti....",
  "Feeling strong and motivated! His is the place where I found myself, to get more healthier, strong and motivated. I’m part of the fitness challenge and I experienced that the workouts and consistency ...",
  "Coming out of Prapti fitness classes I feel energised, happy and ready to start my day. She really pushes you and focuses on the core body areas. I would highly recommend Prapti....",
  "Varied classes with lots of flex Prapti's classes are wonderfully varied. You'll never get bored of the same routine as each class is different. She gives options of easy/hard on every exercise which ...",
  "Prapti is absolutely fantastic !!! She is one of the good things that happened to me during Lockdown. I have been doing her sessions since July and I just love it. Her sessions are not the same, as th...",
  "I have had an amazing transformation after joining the KeepWell Mantra Fitness Routine and Diet Consultations. I managed to hit my weight goal, strengthen my core and increase stamina within the first...",
  "Prapti is amazing fitness trainer. She is professional, highly skilled and organised in her regimes. Many got desirable body transformations by following Prapti’s diverse fitness classes. She is motiv...",
  "One of the most excellent service and… You all feel welcomed and look forward to her sessions. Her advice her motivations are up to the top, from her busy life, kids she never is late for her sessions...",
  "Highly recommended! Prapti is so dedicated, she really motivates you like none other I've sen before. Truly an inspiration. Her exercises are also really challenging but doable and simultaneously full...",
  "Prapti dutt is a amazing trainer Prapti dutt is a amazing trainer, knowledgable, experienced.She works well with her clients and give personal attention to everyones needs and requirements. She has ch...",
  "Amazing experience! Prapti is a true professional who is able to work towards YOUR fitness goals. Her workouts are gruelling but fun, with no two sessions ever the same! Inspirational lady who is cons...",
  "Fantastic trainer Fantastic trainer. Very professional and variety of exercises to choose from. Amazing transformations ...",
  "Ladies highly recommend Keep Well Mantras if you're looking to improve your fitness journey. This community is for ladies/mums who fancy joining a fitness community from the comfort of their home.The ...",
  "I have joined her sessions she is amazing very structured workout sessions where all types of people can join. In love with the morning sessions where you can burn 300-400 cal easily. Highly recommend...",
  "For anyone looking to get fitter, I highly recommend Prapti. I have been a part of her fitness family since January. In 4 months, I have achieved: 1. Immense improvement in core and lower body strengt...",
  "An angel in disguise  I started Prapti ' s sessions soon after my physiotherapy for neck pain was completed. I could barely hold my planks for a few seconds. I have hated going to the gym. I had dec...",
  "Very professional and supportive programme Prapti is very professional in her approach. Her approach to exercises is very supportive as one always have a choice to do higher or lower intensity. The fl...",
  "Prapti is Fantastic and very… Prapti is Fantastic and very professional. She inspired me to start working out . With kids this online sessions have made my life easier. Can’t thank her enough ...",
  "Prapti is an awesome fitness coach - the best I have met! Keep inspiring and motivating people to achieve their fitness goals and adopt a healthy lifestyle. In love with her unique exercises and simpl...",
  "I have recently joined Prapti’s fitness classes and really I am not one of those self motivated people who do regular excercises. But whenever I attend the class which is normally 2-3 times a week it’...",
  "Thank you Prapti for consistently designing and training us on our fitness missions. In just 6 weeks, I believe I can achieve a better body despite my medical conditions with your guided diet plans an...",
  "Amazing full body online sessions. Could feel the pain(good one!) after each session. You are great Prapti so as your style of training. All the best.....",
  "Prapti is a fantastic fitness instructor. Her sessions are so varied and fun. She is motivating and she always helps to push me to do my best. Prapti's online fitness sessions were a god sent to me in...",
  "Excellent and effective work outs Excellent and effective work outs ! Prapti is incredibly inspirational and her work outs are just what you need if you want to build stamina and lose weight …! I high...",
  "This recommendation is for Prapti for the super awesome workout sessions that she conducts on daily basis. I must say these are just not any random session that we see online, these are power packed s...",
  "Prapti’s one to one sessions are very good and tailor made to suit one’s requirement. She is dedicated and has been very helpful in building my strength and weight loss. I would definitely recommend h...",
  "Prapti is the best mentor you can have to reach your fitness goal..it's been just 3 weeks I started following Prapti's diet chart and her high intensity session and must say it works like charm and I ...",
  "I highly recommend Prapti’s Workout sessions. They are so intense, lots of variety. No session is the same. I have been doing her sessions since May2020 and i love it. I have improved on my stamina , ...",
  "Prapti and her amazing body has really motivated me keep fit and reduce weight. Her classes are really good. My journey on the platform of fitness has started and it will end when I reach my destinati...",
  "One of the most excellent service and… You all feel welcomed and look forward to her sessions. Her advice her motivations are up to the top, from her busy life, kids she never is late for her sessions...",
  "You really get results in a short space of time! From the moment I saw Prapti's advert on Facebook to being part of her 6 week challenge, I haven't regretted it one bit! She is motivated, passionate a...",
  "The best thing about keep well mantra… He best thing about keep well mantra is the variety and the community of like minded enthusiasts. You never feel the sense of monotony in the workouts … there’s ...",
  "Monday - Friday: 06:00 AM - 07:00 PM\nSaturday - Sunday: 08:00 AM - 01:00 PM",
  "Prapti Dutt, Level 4 Qualified Fitness Trainer, Nutritionist, and Shadow Healer, with experience supporting thousands of transformations worldwide. These are not surface-level results. This work creates inside-out transformations — where physical change is supported by nervous system regulation, subconscious healing, and sustainable habits.",
];

export const packagesData = {
  content: [
    "Our pricing reflects our unwavering commitment to delivering exceptional quality, ensuring you get the best value for your investment.",
    "Basic package £90 per month",
    "Rockstar package £112 per month",
    "Basic package £247 per quarter",
    "Rockstar package £315 per quarter",
    "CoreSculpt App brings you a plethora of options with Circuit training, Bodyweight strength, Yoga, Pilates, Callisthenics, Resistance & strength training along with nutrition and habit coaching services into one comprehensive platform. Not easy to find such a synergy and an unmatched fusion that transforms your fitness journey into an inspiring adventure!\n\nCoreSculpt introduces you to the first ever library of over 500 follow-along videos by a single trainer! Say goodbye to mere instructions, sample videos and boring schedules, rather watch me, your fitness buddy, sweating it out alongside you, providing you unparalleled motivation in every class.\n\nRewards points, consistency badges, activity streak calendar, client inspirations, healthy eating blogs, my tips and tricks, and that community support – there is lots of fun features to let you empower your fitness journey like never before! CoreSculpt isn’t just another Fitness App, it is a culmination of years of dedication, passion, expertise, experience & knowledge and is an ever-evolving network of women.\n\nIn addition to the monthly subscription packages, you can add on the following features:",
    "Introducing our revolutionary fitness platform that brings the gym experience right to your fingertips - the Ultimate Workout Video Library",
    "Are you tired of the same old workout routines? Do you crave diversity and excitement in your fitness journey? Look no further. With our subscription, you'll gain access to a treasure trove of over 500 workout videos that span a wide spectrum of fitness categories.",
    "Introducing our revolutionary fitness platform that brings the gym experience right to your fingertips - the Ultimate Workout Video Library",
    "Are you tired of the same old workout routines? Do you crave diversity and excitement in your fitness journey? Look no further. With our subscription, you'll gain access to a treasure trove of over 500 workout videos that span a wide spectrum of fitness categories.",
    "Monday - Friday: 06:00 AM - 07:00 PM\nSaturday - Sunday: 08:00 AM - 01:00 PM",
    "Prapti Dutt, Level 4 Qualified Fitness Trainer, Nutritionist, and Shadow Healer, with experience supporting thousands of transformations worldwide. These are not surface-level results. This work creates inside-out transformations — where physical change is supported by nervous system regulation, subconscious healing, and sustainable habits.",
    "Magnetize Your Fitness",
    "Client Transformation",
    "Sign up to a dedicated Habit coach",
    "Customised Fitness & nutrition 1 hour call with Prapti",
    "Customised nutrition plan with Prapti",
    "Join Live Classes conducted by Prapti",
  ]
};
